### ISSUE TITLE
Disable native page routes of next.js. Enable dynamic routing alone.

### ISSUE THREAD

**Issue by jilvin** [ccfcet/moksha#12]

**Comment by asr1191** [comment]
The commit was a temporary fix. It disables native routing because of the flag added to next.config.js

```
const withCSS = require('@zeit/next-css');

let nextCSS = withCSS();
nextCSS.useFileSystemPublicRoutes = false;

module.exports = nextCSS;

```

But, with just that addition, an internal server error occurs when you try to use the default /pages URLs. This is most probably because of the code added to properly integrate Material UI, by injecting CSS into the webpage on server side before being sent to the client side. #8 

This should be dealt with by referring to the `_app.js` , `_document.js` , and `getPageContext.js` files.

**HOWEVER**, by adding a universal route, which directs to an error page, this problem is solved.
```
const routes = require('next-routes')();

routes
  .add({ name: 'home_page', pattern: '/', page: 'index' })
  .add({ name: 'about', pattern: '/about/college', page: 'about/college' })
  .add({ name: 'news', pattern: '/news', page: 'news' })
  .add({ name: 'error', pattern: '/:error', page: 'page' });

module.exports = routes;
```
We should be creating a custom error page eventually, and this route will most certainly be used. Therefore, I don't see a need to change anything else. 

@jilvin If you feel like this issue can be closed, please close it.

**Comment by jilvin** [comment]
For now, this seems the right way to fix this issue. We can re-open this later if necessary.
